### ISSUE TITLE
Image Command not receiving Results..

### ISSUE THREAD

**Issue by Rennet** [LordYusei/CHLib-Bot-For-Chatango#1]
File "C:\Users\user\Desktop\asd\example.py", line 318, in recvPost
    for f in data["items"]:
KeyError: 'items

gives me an error like that.'

**Comment by LordYusei** [comment]
Give me a second to download a zip of the project and test it, and i'll reply with a fix. Seems to work fine in my current project, so we will see. :)

**Comment by LordYusei** [comment]
Oh I see what is wrong. Did you get a Google Image Search API yet?

**Comment by LordYusei** [comment]
Okay, you need to set up a Google Custom Search API and define it. I cannot remember how I did it myself, but this should help. http://stackoverflow.com/questions/8448788/google-custom-search-for-images-only

**Comment by Rennet** [comment]
I did get the API yeah, I am not 100% it's the right one since I haven't dealt with APIs before.

**Comment by Rennet** [comment]
Thanks, got it work.

**Comment by LordYusei** [comment]
Glad it's sorted for you. Apologies for not replying sooner, my laptop has died and the charger melted haha. I'll help you with whatever you need if you need help at all
